name: Deploy to Anycast Servers

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  prepare-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run docs:build
        
      - name: Save SSL files
        run: |
          mkdir -p ssl
          echo "${{ secrets.SSL_CERT }}" > ssl/cert.pem
          echo "${{ secrets.SSL_KEY }}" > ssl/key.pem
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            src/.vuepress/dist
            nginx.conf
            ssl

  deploy-amsterdam:
    needs: prepare-files
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          
      - name: Create env file
        run: echo "VUE_APP_ANYCAST=Amsterdam" > .env
          
      - name: Deploy to Amsterdam
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: anycast-amsterdam.pysio.online
          username: root
          key: ${{ secrets.SSL_PYSIO_PC }}
          script: |
            mkdir -p /usr/share/nginx/html
            mkdir -p /etc/nginx/ssl
            mkdir -p /etc/nginx/conf.d
            systemctl stop nginx || true
            rm -rf /usr/share/nginx/html/*
            rm -rf /etc/nginx/ssl/*
            rm -f /etc/nginx/conf.d/default.conf
        
      - name: Copy files
        uses: appleboy/scp-action@master
        with:
          host: anycast-amsterdam.pysio.online
          username: root
          key: ${{ secrets.SSL_PYSIO_PC }}
          source: "dist/*"
          target: "/usr/share/nginx/html/"
          strip_components: 1

      - name: Copy nginx config and SSL
        uses: appleboy/scp-action@master
        with:
          host: anycast-amsterdam.pysio.online
          username: root
          key: ${{ secrets.SSL_PYSIO_PC }}
          source: "nginx.conf,ssl/*"
          target: "/etc/nginx/"
          strip_components: 1

      - name: Setup nginx
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: anycast-amsterdam.pysio.online
          username: root
          key: ${{ secrets.SSL_PYSIO_PC }}
          script: |
            mv /etc/nginx/nginx.conf /etc/nginx/conf.d/default.conf
            chmod 600 /etc/nginx/ssl/key.pem
            nginx -t
            systemctl start nginx

  deploy-hongkong:
    needs: prepare-files
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          
      - name: Create env file
        run: echo "VUE_APP_ANYCAST=HongKong" > .env
        
      - name: Deploy to HongKong
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: anycast-hongkong.pysio.online
          username: root
          key: ${{ secrets.SSL_PYSIO_PC }}
          script: |
            mkdir -p /usr/share/nginx/html
            mkdir -p /etc/nginx/ssl
            mkdir -p /etc/nginx/conf.d
            systemctl stop nginx || true
            rm -rf /usr/share/nginx/html/*
            rm -rf /etc/nginx/ssl/*
            rm -f /etc/nginx/conf.d/default.conf
        
      - name: Copy files
        uses: appleboy/scp-action@master
        with:
          host: anycast-hongkong.pysio.online
          username: root
          key: ${{ secrets.SSL_PYSIO_PC }}
          source: "dist/*"
          target: "/usr/share/nginx/html/"
          strip_components: 1

      - name: Copy nginx config and SSL
        uses: appleboy/scp-action@master
        with:
          host: anycast-hongkong.pysio.online
          username: root
          key: ${{ secrets.SSL_PYSIO_PC }}
          source: "nginx.conf,ssl/*"
          target: "/etc/nginx/"
          strip_components: 1

      - name: Setup nginx
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: anycast-hongkong.pysio.online
          username: root
          key: ${{ secrets.SSL_PYSIO_PC }}
          script: |
            mv /etc/nginx/nginx.conf /etc/nginx/conf.d/default.conf
            chmod 600 /etc/nginx/ssl/key.pem
            nginx -t
            systemctl start nginx

  deploy-mumbai:
    needs: prepare-files
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          
      - name: Create env file
        run: echo "VUE_APP_ANYCAST=Mumbai" > .env
          
      - name: Deploy to Mumbai
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: anycast-mumbai.pysio.online
          username: root
          key: ${{ secrets.SSL_PYSIO_PC }}
          script: |
            mkdir -p /usr/share/nginx/html
            mkdir -p /etc/nginx/ssl
            mkdir -p /etc/nginx/conf.d
            systemctl stop nginx || true
            rm -rf /usr/share/nginx/html/*
            rm -rf /etc/nginx/ssl/*
            rm -f /etc/nginx/conf.d/default.conf
        
      - name: Copy files
        uses: appleboy/scp-action@master
        with:
          host: anycast-mumbai.pysio.online
          username: root
          key: ${{ secrets.SSL_PYSIO_PC }}
          source: "dist/*"
          target: "/usr/share/nginx/html/"
          strip_components: 1

      - name: Copy nginx config and SSL
        uses: appleboy/scp-action@master
        with:
          host: anycast-mumbai.pysio.online
          username: root
          key: ${{ secrets.SSL_PYSIO_PC }}
          source: "nginx.conf,ssl/*"
          target: "/etc/nginx/"
          strip_components: 1

      - name: Setup nginx
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: anycast-mumbai.pysio.online
          username: root
          key: ${{ secrets.SSL_PYSIO_PC }}
          script: |
            mv /etc/nginx/nginx.conf /etc/nginx/conf.d/default.conf
            chmod 600 /etc/nginx/ssl/key.pem
            nginx -t
            systemctl start nginx

  deploy-newjersey:
    needs: prepare-files
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          
      - name: Create env file
        run: echo "VUE_APP_ANYCAST=NewJersey" > .env
          
      - name: Deploy to NewJersey
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: anycast-newjersey.pysio.online
          username: root
          key: ${{ secrets.SSL_PYSIO_PC }}
          script: |
            mkdir -p /usr/share/nginx/html
            mkdir -p /etc/nginx/ssl
            mkdir -p /etc/nginx/conf.d
            systemctl stop nginx || true
            rm -rf /usr/share/nginx/html/*
            rm -rf /etc/nginx/ssl/*
            rm -f /etc/nginx/conf.d/default.conf
        
      - name: Copy files
        uses: appleboy/scp-action@master
        with:
          host: anycast-newjersey.pysio.online
          username: root
          key: ${{ secrets.SSL_PYSIO_PC }}
          source: "dist/*"
          target: "/usr/share/nginx/html/"
          strip_components: 1

      - name: Copy nginx config and SSL
        uses: appleboy/scp-action@master
        with:
          host: anycast-newjersey.pysio.online
          username: root
          key: ${{ secrets.SSL_PYSIO_PC }}
          source: "nginx.conf,ssl/*"
          target: "/etc/nginx/"
          strip_components: 1

      - name: Setup nginx
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: anycast-newjersey.pysio.online
          username: root
          key: ${{ secrets.SSL_PYSIO_PC }}
          script: |
            mv /etc/nginx/nginx.conf /etc/nginx/conf.d/default.conf
            chmod 600 /etc/nginx/ssl/key.pem
            nginx -t
            systemctl start nginx

  deploy-tokyo:
    needs: prepare-files
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          
      - name: Create env file
        run: echo "VUE_APP_ANYCAST=Tokyo" > .env
          
      - name: Deploy to Tokyo
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: anycast-tokyo.pysio.online
          username: root
          key: ${{ secrets.SSL_PYSIO_PC }}
          script: |
            mkdir -p /usr/share/nginx/html
            mkdir -p /etc/nginx/ssl
            mkdir -p /etc/nginx/conf.d
            systemctl stop nginx || true
            rm -rf /usr/share/nginx/html/*
            rm -rf /etc/nginx/ssl/*
            rm -f /etc/nginx/conf.d/default.conf
        
      - name: Copy files
        uses: appleboy/scp-action@master
        with:
          host: anycast-tokyo.pysio.online
          username: root
          key: ${{ secrets.SSL_PYSIO_PC }}
          source: "dist/*"
          target: "/usr/share/nginx/html/"
          strip_components: 1

      - name: Copy nginx config and SSL
        uses: appleboy/scp-action@master
        with:
          host: anycast-tokyo.pysio.online
          username: root
          key: ${{ secrets.SSL_PYSIO_PC }}
          source: "nginx.conf,ssl/*"
          target: "/etc/nginx/"
          strip_components: 1

      - name: Setup nginx
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: anycast-tokyo.pysio.online
          username: root
          key: ${{ secrets.SSL_PYSIO_PC }}
          script: |
            mv /etc/nginx/nginx.conf /etc/nginx/conf.d/default.conf
            chmod 600 /etc/nginx/ssl/key.pem
            nginx -t
            systemctl start nginx

  deploy-summary:
    needs: [deploy-amsterdam, deploy-hongkong, deploy-mumbai, deploy-newjersey, deploy-tokyo]
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Summary
        run: |
          echo "### 部署完成! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "| 服务器 | 状态 | 域名 |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- | --- |" >> $GITHUB_STEP_SUMMARY
          echo "| Amsterdam | ✅ | anycast-amsterdam.pysio.online |" >> $GITHUB_STEP_SUMMARY
          echo "| HongKong | ✅ | anycast-hongkong.pysio.online |" >> $GITHUB_STEP_SUMMARY
          echo "| Mumbai | ✅ | anycast-mumbai.pysio.online |" >> $GITHUB_STEP_SUMMARY
          echo "| NewJersey | ✅ | anycast-newjersey.pysio.online |" >> $GITHUB_STEP_SUMMARY
          echo "| Tokyo | ✅ | anycast-tokyo.pysio.online |" >> $GITHUB_STEP_SUMMARY
